language: python
services:
  - redis-server
python:
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
install:
  - pip install .
  - pip install coveralls
  - pip install -r requirements-dev.txt
script:
  - mamba --enable-coverage
# after_success:
# - coverage combine
# - coverage report
# - coveralls
